#pragma once

// A motor request generated by the ball-search state machine.  The caller
// owns the actual motor driver and applies these speeds.
struct BallSearchCommand
{
  int left_speed;
  int right_speed;
  bool target_found;
  bool complete;
};

// Begins an in-place ultrasonic scan for an object in the end zone.
void begin_ball_search();

// Enable concise Serial diagnostics for the standalone search/retrieval tests.
// Leave disabled in normal robot operation to avoid serial-output timing cost.
void set_ball_search_debug(bool enabled);

// Advance the search state machine and return the requested motor command.
// Call this repeatedly after begin_ball_search().
BallSearchCommand update_ball_search();
